SELECT *
/*FROM platzi.alumnos
--FORMAS FACILES:
FETCH FIRST 1 ROWS ONLY; --BUSCA SÓLO LAS PRIMERAS 1 FILAS
LIMIT 1; -- ESTO LIMITA AL PRIMER REGISTRO*/

-- VEMOS LAS WINDOWS FUNCTIONS: ES LA RELACION QUE EXISTE ENTRE EL ROW QUE QUEREMOS MEDIR Y LA TOTALIDAD DE ROWS EN UN GRUPO
FROM (
	/*DENTRO HACEMOS UN SUBSELECT
	CON ROW_NUMBER() TRAEME CUAL ES EL NUMERO DE REGISTRO INDEPENDIENTEMENTE DE CUALQUIER CRITERIO QUE PONGA
	CON OVER() LE INDICAMOS CON QUE DATOS LOS QUEREMOS MEDIR
	CON AS LE ASIGNO UN ALIAS 
	CON * TRAEMOS TODOS LOS CAMPOS PARA QUE SEA UNA TABLA NORMAL DESPUES DE LOS ROWS_ID
	*/
	SELECT ROW_NUMBER() OVER() AS row_id, *
	FROM platzi.alumnos
) AS alumnos_with_row_num
-- SI QUEREMOS LIMITAR EL ROW_ID LO INDICAMOS CON WHERE
WHERE row_id = 5;
;